name: Build and Push Docker image to ACR

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
    
  
env:
  REGISTRY_NAME: acrapl20031  # Set your registry name here
  IMAGE_NAME: app2003  # Set your image name here

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: "Az CLI login"
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}